CREATE TABLE sensor (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30)
);


CREATE TABLE measurement (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value real NOT NULL CHECK ( value > -100 and value < 100),
    raining boolean NOT NULL,
    measurement_data_time timestamp NOT NULL,
    sensor_id int NOT NULL REFERENCES sensor(id)
);